### ISSUE TITLE
Error when run transformers

### ISSUE THREAD

**Issue by HGGshiwo** [btx0424/OmniDrones#18]
When I use velocity control, there occur a issue, I think the following code in the file ```omni_drones/utils/torchrl/transforms.py``` should change from: 
```
input_spec[("_action_spec", *self.action_key)] = spec
```
to
```
input_spec[("full_action_spec", *self.action_key)] = spec
```

**Comment by btx0424** [comment]
Yes. Thanks for pointing that out. I will try to make a better interface for controllers shortly.
