### ISSUE TITLE
rotor is not rotating

### ISSUE THREAD

**Issue by HGGshiwo** [btx0424/OmniDrones#20]
In my case, the rotor is not rotating when do simultation. Though it doesn't influence the results, but it looks weird. I wonder is this a bug or something?

By the way, I use Hummingbird for simulation.

**Comment by btx0424** [comment]
Hello there, currently we do not actually rotate the rotors so as to cut the simulation cost. The moments are not generated from rotating but are directly applied to the CoM of the drone.

This has something to do with how joints are controlled and how torques are generated in Isaac Sim. I am thinking about adding an actual "rotor" actuator in the next version.

People from NVIDIA told me that 2023.1.0 will come out around the end of this month, so we will look into that shortly.

For now, I can just turn on the rotation (maybe slowed down by a factor) to make things look nicer.

**Comment by HGGshiwo** [comment]
Thanks for your quick reply, and looking forward to your updates.
