### ISSUE TITLE
TorchRL, TensorDict version is not supported (+ Fix minor things)

### ISSUE THREAD

**Issue by finani** [btx0424/OmniDrones#30]
Thank you for your tremendous and fantastic approach, first.
It would be an enormous help to related works.

Nvidia Isaac Sim has a built-in Python, and its version is 3.7.
I think that is the reason the conda environment is python=3.7 ([Installation](https://omnidrones.readthedocs.io/en/latest/installation.html)).

A few days ago, I was trying to install OmniDrones and encountered an issue related to 'TensorDictParams'.
I have checked it is a new feature in TensorDict 0.2.0 ([PR](https://github.com/pytorch/tensordict/pull/500)).
So, I tried to install TensorDict 0.2.0 ([pip](https://pypi.org/project/tensordict/0.2.0/)) and TorchRL 0.2.0 ([pip](https://pypi.org/project/torchrl/0.2.0/)) from pip, but they all support Python only from 3.8 to 3.11.
I got errors about Processing from Typing, which is a new feature in Python 3.8 when I installed them from git repos and ran OmniDrones.

Thankfully, I was able to successfully install and test OmniDrones with the newly updated guide.
However, I am just wondering if it will be okay in future versions.
(Is it okay to use packages that support Python 3.8 or higher in a Python 3.7 environment?)

I also fixed small problems with the docs and setup.py.
Thanks!

**Comment by btx0424** [comment]
Hi there! 

The next release of Isaac Sim will support Python 3.8 to 3.10, [according to the staff](https://forums.developer.nvidia.com/t/python-3-7-eol/253269). 

And thanks for your contribution! As some main dependencies are still not stable, I think there are currently some minor problems in the project. Feel free to raise an issue or PR if you encounter any.
