### ISSUE TITLE
_RigidPrimView and _ArticulationView

### ISSUE THREAD

**Issue by barrosiuri** [btx0424/OmniDrones#37]
I am not reporting a bug, but if you could, I would like some clarification on two classes. Could you explain me why did you decided to make your own RigidPrimView and ArticulationView?

**Comment by btx0424** [comment]
Hi there, thanks for your interest in our project.

I created the wrapper classes to better deal with the situations where each environment has multiple bodies/articulations of the same kind. For example, suppose we have `/World/envs/env_*/Robot_0` and `/World/envs/env_*/Robot_1`, the original view classes give a view of shape [count=num_envs * 2,]. The new classes virtually "reshape" them into [num_envs, 2], making it more convenient for environment-level set/get.

**Comment by barrosiuri** [comment]
Thank you for the info. If I have more questions, should I post them here?

**Comment by btx0424** [comment]
Sure. Feel free to raise an issue, email me, or join the discord if you have any questions.
