### ISSUE TITLE
"it is illegal to call this method if PxSceneFlag::eENABLE_DIRECT_GPU_API is enabled!" while setting headless=False

### ISSUE THREAD

**Issue by jinwoolee1230** [btx0424/OmniDrones#50]
Dear Maintainers,

First of all, I really do appreciate your effort and work done on this project and I strongly believe this project is going to be a game-changer in RL-based control on UAV. I hope I could follow up on your simulation setup instruction and work on it.

I was following up the Omnidrones 0.1 documents for the installation, and I had slight warnings during the installation process but did not have any critical errors. So I reached to verification part of your instruction on "Workstation installation".

When I ran the command:
`python3 train.py algo=ppo headless=true wandb.entity=YOUR_WANDB_ENTITY`
it worked for many iterations without problem.

Aftter this, I wanted to check the progress of in the simulation so I disabled healess option on command so I ran this:
`python3 train.py algo=ppo headless=false wandb.entity=YOUR_WANDB_ENTITY`
and I have encountered numerous repitition of following error:

`2024-03-01 09:53:25 [132,786ms] [Error] [omni.physx.plugin] PhysX error: PxArticulationLink::setGlobalPose(): it is illegal to call this method if PxSceneFlag::eENABLE_DIRECT_GPU_API is enabled!, FILE /buildAgent/work/eb2f45c4acc808a0/physx/source/physx/src/NpArticulationLink.cpp, LINE 343
`
I thought this is issue with some kind of initial setting of the simulation but I could not find any of related codes.. I might be lacking in skills but I think some of the other users are suffering from same error message.

could you please give me some insights about this issue?

Thank you so much for creating this amazing platform, and I cannot wait to do some RL project on this.

**Comment by jinwoolee1230** [comment]
Thank you for responding. It may be similar issue from #49 but mine is working well in headless=True. I am now using 2023.1.1 so I will try again with 2023.1.0! Thank you for the kind instruction

**Comment by jinwoolee1230** [comment]
It worked perfectly with 23.1.0 hotfix version. Thank you so much and closing the issue

**Comment by Everloom-129** [comment]
Hi, Isaac Sim 2023.1.1 is not supported after 4.0.0 and 4.0.1 released, it seems the Omnidrones also shift to newer version. but I kept meeting this problem, do you know how to solve it? @jinwoolee1230

**Comment by super-NOV-a** [comment]
Did you solve this problem with a newer version of the Isaac Sim? I met the same problem with version 4.1.0 on both headless=true and headless=flase situations. @Everloom-129

**Comment by zzj404** [comment]
@btx0424  I met the same problem with version 4.1.0 on both headless=true and headless=flase situations.

**Comment by Ecstasy-EC** [comment]
> [@btx0424](https://github.com/btx0424) It is exactly the same problem as in the latest IsaacLab. Do you know why it arises? I can try to solve it. I have finished migrating the codes to IsaacSim 4.5 and i guess this is the last one I need to solve.

The problem arises from this file. If anyone can help, we could start with this file to see which function in Omnidrone triggers the error.
https://github.com/NVIDIA-Omniverse/PhysX/blob/2264315594478a9aa0bda3464761a666fa107d76/physx/source/physx/src/NpArticulationLink.cpp#L4

**Comment by Ecstasy-EC** [comment]
> > [@btx0424](https://github.com/btx0424) It is exactly the same problem as in the latest IsaacLab. Do you know why it arises? I can try to solve it. I have finished migrating the codes to IsaacSim 4.5 and i guess this is the last one I need to solve.
> 
> The problem arises from this file. If anyone can help, we could start with this file to see which function in Omnidrone triggers the error. https://github.com/NVIDIA-Omniverse/PhysX/blob/2264315594478a9aa0bda3464761a666fa107d76/physx/source/physx/src/NpArticulationLink.cpp#L351

The bug is located at this line:
https://github.com/btx0424/OmniDrones/blob/main/omni_drones/views/__init__.py#L67

I guess we need to modify `ArticulationView` using the latest API.

**Comment by Everloom-129** [comment]
Hi all, I was able to fix this issue by:
- setting issacsim to 4.1, same version as readme mentioned
- setting issaclab to newest version
- reset the bash file loading

for multiple GPU, there exists some compatibility issue, maybe you will need to force CUDA=1 or stay at a lower version of issacsim

**Comment by Ecstasy-EC** [comment]
> > > [@btx0424](https://github.com/btx0424) It is exactly the same problem as in the latest IsaacLab. Do you know why it arises? I can try to solve it. I have finished migrating the codes to IsaacSim 4.5 and i guess this is the last one I need to solve.
> > 
> > 
> > The problem arises from this file. If anyone can help, we could start with this file to see which function in Omnidrone triggers the error. https://github.com/NVIDIA-Omniverse/PhysX/blob/2264315594478a9aa0bda3464761a666fa107d76/physx/source/physx/src/NpArticulationLink.cpp#L351
> 
> The bug is located at this line: https://github.com/btx0424/OmniDrones/blob/main/omni_drones/views/__init__.py#L67
> 
> I guess we need to modify `ArticulationView` using the latest API.

Done. See #94

**Comment by thethaibinh** [comment]
> > > > [@btx0424](https://github.com/btx0424) It is exactly the same problem as in the latest IsaacLab. Do you know why it arises? I can try to solve it. I have finished migrating the codes to IsaacSim 4.5 and i guess this is the last one I need to solve.
> > > 
> > > 
> > > The problem arises from this file. If anyone can help, we could start with this file to see which function in Omnidrone triggers the error. https://github.com/NVIDIA-Omniverse/PhysX/blob/2264315594478a9aa0bda3464761a666fa107d76/physx/source/physx/src/NpArticulationLink.cpp#L351
> > 
> > 
> > The bug is located at this line: https://github.com/btx0424/OmniDrones/blob/main/omni_drones/views/__init__.py#L67
> > I guess we need to modify `ArticulationView` using the latest API.
> 
> Done. See [#94](https://github.com/btx0424/OmniDrones/pull/94)

Please have a look, bro https://github.com/btx0424/OmniDrones/pull/94#issuecomment-3138716189
