### ISSUE TITLE
wait too long when run train.py

### ISSUE THREAD

**Issue by Bruce-Si** [btx0424/OmniDrones#74]
When I run `python train.py`, I always get the following error. Sometimes it will work after half an hour, sometimes it doesn't work no matter how long I waited. Do you have any view on it? tks!

<img width="1799" alt="Screenshot from 2024-06-26 15-14-54" src="https://github.com/btx0424/OmniDrones/assets/55371740/ee83c1e9-06bc-49bb-93c5-5bdf5084e69a">

**Comment by INDEX108** [comment]
I had the same problem : c100 "mdl"
